version: '3.2'
services:
  localstack:
    image: localstack/localstack:0.10.6
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8082:8082'
    environment:
      - SERVICES=s3:4566
      - HOSTNAME_EXTERNAL=localhost
      - PORT_WEB_UI=8082
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ACCESS_KEY_ID=dummy
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
