version: '3.2'
services:
  localstack:
    image: localstack/localstack:0.10.6
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8082:8082'
    environment:
      - SERVICES=s3:4566
      - HOSTNAME_EXTERNAL=localhost
      - PORT_WEB_UI=8082
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_SECRET_ACCESS_KEY=oFJXVjVvlBRPTeTbYspdGaeVUD8S6OfP0dZdilCD
      - AWS_ACCESS_KEY_ID=AKIAQ3JUWAXV2C246P6O
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'